version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - ergonomiška
  - išlygiagretintas
  - kategorizavimo
  - konteinerizuotoje
  - produkcinė
  - produkcinei
  - produkcinėje
ignoreWords: []
import: []
enabled: true
language: en,lt
